### ISSUE TITLE
NPR Skill Bug

### ISSUE THREAD

**Issue by kfezer** [MycroftAI/mycroft-core#585]
https://community.mycroft.ai/t/pycroft-hey-mycroft-play-the-news-play-duplicate-news-mp3s/1464

Sounds like we might need to adjust the link we are fetching from. Sometimes returns nothing and sometimes returns duplciates.

**Comment by southernseas** [comment]
I have run some tests yesterday which had the same duplicate problem inc playing old alarms and then today where there was no problem.
My theory is that is it related to periodically slow internet ( copper ) and the MP3 play is starting before the MP3 has downloaded.
e.g. the code should download the MP3 to  unique name ( to stop playing any junk files ), 
then check the file exists before playing the MP3
Re code inspection
Have been looking for the source on my Pi and grep-ed
/home/mycroft/.mycroft/skills/NPRNewsSkill
But there is not .py code in there
Q:Where does the skills code live on a RPi?

**Comment by apsillers** [comment]
I just experienced this bug as well. In my case, it played about a second or two of the audio and then went quiet. When I tried again, it played a new one from the beginning and the original one, one second ahead out of sync.

My hunch is that something is incorrectly halting the audio playback, and then when another audio playback starts, it unpauses.

This was using Picroft image, playing 3.5 audio jack output, if it makes any difference. I'll try with HDMI out shortly and compare.

**Comment by forslund** [comment]
Hi Andrew,

Can you check the version of mycroft installed?

apt-list mycroft-core

or

python
from mycroft.version import CORE_VERSION_STR
print CORE_VERSION_STR


I was under the impression that this was fixed so it would be good to have the version. I'm asking because I know picroft has not received updates in a while. (Soon though)

**Comment by apsillers** [comment]
Using the Python approach, `CORE_VERSION_STR` is `0.8.1`.

In case it's not yet fixed: today, I had the news play successfully once, and then I reproduced this bug again on another try. The news starts playing while Mycroft is still talking ("Here's the news," or something), and when Mycroft finishes talking then the NPR audio terminates as well. (Though, that overlap is what happened on the successful run as well, but the NPR track didn't stop that time.)

**Comment by forslund** [comment]
0.8.1 is quite old but I will definitely see if I can reproduce using the current version.

Thanks for reporting.

**Comment by forslund** [comment]
Closing this one since it's releated to the npr-news-skill and I believe the issue is fixed.
